# Site settings
title: Comox Valley Canines
description: Comox Valley Canines is a community-led advocacy organization committed to providing education and information for dog guardians and pushing local governments for more dog-friendly spaces.
cover: /assets/images/cover.jpg
logo: /assets/images/logo_title.png
favicon: /assets/images/favicon.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://comoxvalleycanines.ca" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
facebook: facebook
twitter: twitter

#Additional Pages
dog-awareness: dog-awareness
initiatives: initiatives
local-spots: local-spots
about-us: about-us
contacts: contacts
faq: faq


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: false

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: bencornwellmott #github username
repo: cvcanines #github repository
branch: master #branch
relative_source: ../cvcanines/ #source directory
destination: ./_site/ #destination directory
production_url:  https://comoxvalleycanines.ca/
source_url:  https://github.com/bencornwellmott/cvcanines #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
